## **DESCARGAR DATOS DE CASH FLOW DEL INDICE S&P500**

**Nota Importante: Todos los ejemplos que vamos a ver a lo largo de este cuaderno son solo para fines educativos y no constituyen recomendación de inversión.**

En este módulo aprenderemos a obtener grandes volúmenes de datos financieros relacionados con el área de pérdidas y ganancias.

Para ello, utilizaremos la librería `yfinance`. Para instalarla, sigue estos pasos:

1. Haz clic en **Terminal** (en el menú superior) o accede al **Command Prompt (CMD)** / **Análisis del Sistema** desde la barra de herramientas.
2. Escribe el siguiente comando:

    ```bash
    pip install yfinance
    ```

**Nota importante:** Las librerías de Python se actualizan con frecuencia, lo que puede hacer que algunas de sus funciones queden obsoletas. Es importante mantenerlas actualizadas. Para actualizar una librería, utiliza el siguiente comando:

```bash
pip install yfinance --upgrade --no-cache-dir
```


Si deseas verificar la versión instalada de una librería, utiliza el siguiente comando:

```bash
pip show yfinance
```

**Estas instrucciones son aplicables a cualquier librería de Python.**

# Pasos a seguir:

1. Utilizar el listado de empresas cotizadas del S&P 500 creado en el módulo anterior para acceder a la librería `yfinance`.
2. Implementar un bucle `for` que itere sobre cada uno de los tickers.
3. Construir una tabla que consolide los datos de `Cash Flow` de cada empresa.

**Antes de nada importamos las librerias que vamos a necesitar para este módulo**

In [1]:
# Preparamos la celda para importar las librerias necesarias para el proyecto, en este caso pandas, numpy y yfinance. Si no se encuentran instaladas, se mostrará un mensaje de error indicando cuál es la librería faltante y cómo instalarla.

# Importamos las librerías necesarias
    # pandas: para manipulación y análisis de datos en forma de tablas (DataFrames)
    # requests: para hacer peticiones HTTP y descargar contenido de páginas web
    # yfinance: para obtener datos financieros desde Yahoo Finance
    # datetime y timedelta: para manejar fechas y tiempos
    # time: para medir el tiempo de ejecución de ciertas partes del código

try:
    import yfinance as yf # la más importante
    import pandas as pd
    import requests
    from datetime import datetime, timedelta
    import numpy as np
    import time
    from io import StringIO
    print("Todas las librerías se han importado correctamente")
except ImportError as e:
    print(f"Error al importar una o más librerías: {e}, es problable que necesites instalar esta libreria usando pip install nombre_de_libreria")

Todas las librerías se han importado correctamente

**1. Crear el listado de tickers**

Documentación disponible en el archivo extraer_tickers_SP500.ipynb

In [2]:
########---CARGAMOS LOS TICKERS DEL S&P 500 DESDE WIKIPEDIA---########

# URL de la página de Wikipedia que contiene la lista de empresas del S&P 500
url_sp500 = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"

# Definimos un encabezado HTTP (User-Agent)
headers = {
    "User-Agent": "Mozilla/5.0"
}

# Hacemos la petición GET a Wikipedia y verificamos que sea exitosa
response = requests.get(url_sp500, headers=headers)
response.raise_for_status()  # Lanza un error si la página no respondió correctamente

# Convertimos el HTML de la respuesta en un buffer de texto en memoria.
# Esto evita problemas de pandas/lxml al leer HTML directamente desde URLs en algunas versiones de Python.
html_io = StringIO(response.text)

# Leemos todas las tablas del HTML con pandas
# pd.read_html devuelve una lista de DataFrames; seleccionamos la primera tabla
# que contiene la lista principal de empresas del S&P 500.
sp500 = pd.read_html(html_io)[0]

# Renombramos algunas columnas para que tengan nombres más simples e intuitivos.
sp500 = sp500.rename(
    columns={
        'Symbol': 'ticker',
        'Security': 'name',
        'GICS Sector': 'sector'
            }
        )

# Seleccionamos únicamente las columnas que nos interesan, eliminando información innecesaria
sp500_clean = sp500[['ticker', 'name', 'sector']]

# En este punto, sp500_clean contiene:
# - ticker: símbolo bursátil de la empresa
# - name: nombre de la empresa
# - sector: sector económico al que pertenece

# Creamos la lista de tickers a partir de la columna 'ticker' del DataFrame limpio, añadimos unique() para evitar duplicados y tolist() para convertir el resultado en una lista de Python
tickers_list = sp500_clean['ticker'].unique().tolist()

print(tickers_list)

['MMM', 'AOS', 'ABT', 'ABBV', 'ACN', 'ADBE', 'AMD', 'AES', 'AFL', 'A', 'APD', 'ABNB', 'AKAM', 'ALB', 'ARE', 'ALGN', 'ALLE', 'LNT', 'ALL', 'GOOGL', 'GOOG', 'MO', 'AMZN', 'AMCR', 'AEE', 'AEP', 'AXP', 'AIG', 'AMT', 'AWK', 'AMP', 'AME', 'AMGN', 'APH', 'ADI', 'AON', 'APA', 'APO', 'AAPL', 'AMAT', 'APP', 'APTV', 'ACGL', 'ADM', 'ARES', 'ANET', 'AJG', 'AIZ', 'T', 'ATO', 'ADSK', 'ADP', 'AZO', 'AVB', 'AVY', 'AXON', 'BKR', 'BALL', 'BAC', 'BAX', 'BDX', 'BRK.B', 'BBY', 'TECH', 'BIIB', 'BLK', 'BX', 'XYZ', 'BK', 'BA', 'BKNG', 'BSX', 'BMY', 'AVGO', 'BR', 'BRO', 'BF.B', 'BLDR', 'BG', 'BXP', 'CHRW', 'CDNS', 'CPT', 'CPB', 'COF', 'CAH', 'CCL', 'CARR', 'CVNA', 'CAT', 'CBOE', 'CBRE', 'CDW', 'COR', 'CNC', 'CNP', 'CF', 'CRL', 'SCHW', 'CHTR', 'CVX', 'CMG', 'CB', 'CHD', 'CIEN', 'CI', 'CINF', 'CTAS', 'CSCO', 'C', 'CFG', 'CLX', 'CME', 'CMS', 'KO', 'CTSH', 'COIN', 'CL', 'CMCSA', 'FIX', 'CAG', 'COP', 'ED', 'STZ', 'CEG', 'COO', 'CPRT', 'GLW', 'CPAY', 'CTVA', 'CSGP', 'COST', 'CTRA', 'CRH', 'CRWD', 'CCI', 'CSX', 'CMI', 'CVS', 'DHR', 'DRI', 'DDOG', 'DVA', 'DECK', 'DE', 'DELL', 'DAL', 'DVN', 'DXCM', 'FANG', 'DLR', 'DG', 'DLTR', 'D', 'DPZ', 'DASH', 'DOV', 'DOW', 'DHI', 'DTE', 'DUK', 'DD', 'ETN', 'EBAY', 'ECL', 'EIX', 'EW', 'EA', 'ELV', 'EME', 'EMR', 'ETR', 'EOG', 'EPAM', 'EQT', 'EFX', 'EQIX', 'EQR', 'ERIE', 'ESS', 'EL', 'EG', 'EVRG', 'ES', 'EXC', 'EXE', 'EXPE', 'EXPD', 'EXR', 'XOM', 'FFIV', 'FDS', 'FICO', 'FAST', 'FRT', 'FDX', 'FIS', 'FITB', 'FSLR', 'FE', 'FISV', 'F', 'FTNT', 'FTV', 'FOXA', 'FOX', 'BEN', 'FCX', 'GRMN', 'IT', 'GE', 'GEHC', 'GEV', 'GEN', 'GNRC', 'GD', 'GIS', 'GM', 'GPC', 'GILD', 'GPN', 'GL', 'GDDY', 'GS', 'HAL', 'HIG', 'HAS', 'HCA', 'DOC', 'HSIC', 'HSY', 'HPE', 'HLT', 'HOLX', 'HD', 'HON', 'HRL', 'HST', 'HWM', 'HPQ', 'HUBB', 'HUM', 'HBAN', 'HII', 'IBM', 'IEX', 'IDXX', 'ITW', 'INCY', 'IR', 'PODD', 'INTC', 'IBKR', 'ICE', 'IFF', 'IP', 'INTU', 'ISRG', 'IVZ', 'INVH', 'IQV', 'IRM', 'JBHT', 'JBL', 'JKHY', 'J', 'JNJ', 'JCI', 'JPM', 'KVUE', 'KDP', 'KEY', 'KEYS', 'KMB', 'KIM', 'KMI', 'KKR', 'KLAC', 'KHC', 'KR', 'LHX', 'LH', 'LRCX', 'LW', 'LVS', 'LDOS', 'LEN', 'LII', 'LLY', 'LIN', 'LYV', 'LMT', 'L', 'LOW', 'LULU', 'LYB', 'MTB', 'MPC', 'MAR', 'MRSH', 'MLM', 'MAS', 'MA', 'MTCH', 'MKC', 'MCD', 'MCK', 'MDT', 'MRK', 'META', 'MET', 'MTD', 'MGM', 'MCHP', 'MU', 'MSFT', 'MAA', 'MRNA', 'MOH', 'TAP', 'MDLZ', 'MPWR', 'MNST', 'MCO', 'MS', 'MOS', 'MSI', 'MSCI', 'NDAQ', 'NTAP', 'NFLX', 'NEM', 'NWSA', 'NWS', 'NEE', 'NKE', 'NI', 'NDSN', 'NSC', 'NTRS', 'NOC', 'NCLH', 'NRG', 'NUE', 'NVDA', 'NVR', 'NXPI', 'ORLY', 'OXY', 'ODFL', 'OMC', 'ON', 'OKE', 'ORCL', 'OTIS', 'PCAR', 'PKG', 'PLTR', 'PANW', 'PSKY', 'PH', 'PAYX', 'PAYC', 'PYPL', 'PNR', 'PEP', 'PFE', 'PCG', 'PM', 'PSX', 'PNW', 'PNC', 'POOL', 'PPG', 'PPL', 'PFG', 'PG', 'PGR', 'PLD', 'PRU', 'PEG', 'PTC', 'PSA', 'PHM', 'PWR', 'QCOM', 'DGX', 'Q', 'RL', 'RJF', 'RTX', 'O', 'REG', 'REGN', 'RF', 'RSG', 'RMD', 'RVTY', 'HOOD', 'ROK', 'ROL', 'ROP', 'ROST', 'RCL', 'SPGI', 'CRM', 'SNDK', 'SBAC', 'SLB', 'STX', 'SRE', 'NOW', 'SHW', 'SPG', 'SWKS', 'SJM', 'SW', 'SNA', 'SOLV', 'SO', 'LUV', 'SWK', 'SBUX', 'STT', 'STLD', 'STE', 'SYK', 'SMCI', 'SYF', 'SNPS', 'SYY', 'TMUS', 'TROW', 'TTWO', 'TPR', 'TRGP', 'TGT', 'TEL', 'TDY', 'TER', 'TSLA', 'TXN', 'TPL', 'TXT', 'TMO', 'TJX', 'TKO', 'TTD', 'TSCO', 'TT', 'TDG', 'TRV', 'TRMB', 'TFC', 'TYL', 'TSN', 'USB', 'UBER', 'UDR', 'ULTA', 'UNP', 'UAL', 'UPS', 'URI', 'UNH', 'UHS', 'VLO', 'VTR', 'VLTO', 'VRSN', 'VRSK', 'VZ', 'VRTX', 'VTRS', 'VICI', 'V', 'VST', 'VMC', 'WRB', 'GWW', 'WAB', 'WMT', 'DIS', 'WBD', 'WM', 'WAT', 'WEC', 'WFC', 'WELL', 'WST', 'WDC', 'WY', 'WSM', 'WMB', 'WTW', 'WDAY', 'WYNN', 'XEL', 'XYL', 'YUM', 'ZBRA', 'ZBH', 'ZTS']

**2. Conexión con YahooFinance, bucle con tickers y creación de tabla con cifras de balance**

El proceso es el siguiente:

    - Creamos una Tabla vacia a la que añadiremos los datos con cada iteración

    - Vamos a abrir un bucle en el que vamos a iterar cada ticker

    - Dentro de cada iteración, vamos a descargar los datos de balance de cada ticker, en todos los años disponibles que tengamos y lo añadiremos a la tabla

In [3]:
#Creamos una Tabla vacia a la que añadiremos los datos con cada iteración
df_cash_flow = pd.DataFrame()

print("Cargando datos de cash flow de los tickers del S&P 500...")

#Vamos a abrir un bucle en el que vamos a iterar cada ticker, ab rimos un for loop
for ticker in tickers_list:
    #Mensaje para saber en qué ticker estamos
    print(ticker)
    #Descargamos los datos de cada ticker
    stock = yf.Ticker(ticker)
    #Dentro de cada iteración, vamos a descargar los datos de cash flow de cada ticker, en todos los años disponibles que tengamos y lo añadiremos a la tabla
    ### LA SIGUIENTE LINEA DE CODIGO ES LA UNICA QUE CAMBIA RESPECTO A OTROS MÓDULOS
    cash_flow = stock.cashflow 
    #Transponemos la tabla para que las fechas sean filas y no columnas
    cash_flow_t = cash_flow.T  
    #hacemos unpivot para tener una tabla más manejable en la que cada una de los capitulos del balance esté en una fila y no en columnas
    cash_flow_unpiv = cash_flow_t.reset_index().melt(id_vars='index', var_name='Account', value_name='Value')  # Unpivoting
    #Añadimos una columna con el ticker para identificar cada empresa
    cash_flow_unpiv['ticker'] = ticker
    #Concatenamos los datos descargados a la tabla vacia creada anteriormente
    # Este ultimo paso es crucial para ir acumulando los datos de cada ticker en un solo DataFrame
    df_cash_flow = pd.concat([df_cash_flow, cash_flow_unpiv], ignore_index=True)

# Tenemos el dataframe construido, ahora renombramos las columnas para que tengan nombres más claros
# Renombramos la columna 'index' a 'date' para mayor claridad
df_cash_flow = df_cash_flow.rename(columns={'index': 'date'
                                        , 'Account': 'account'
                                        , 'Value': 'value'})

# Muestra del DataFrame resultante
df_cash_flow.head()

Cargando datos de cash flow de los tickers del S&P 500...
MMM
AOS
ABT
ABBV
ACN
ADBE
AMD
AES
AFL
A
APD
ABNB
AKAM
ALB
ARE
ALGN
ALLE
LNT
ALL
GOOGL
GOOG
MO
AMZN
AMCR
AEE
AEP
AXP
AIG
AMT
AWK
AMP
AME
AMGN
APH
ADI
AON
APA
APO
AAPL
AMAT
APP
APTV
ACGL
ADM
ARES
ANET
AJG
AIZ
T
ATO
ADSK
ADP
AZO
AVB
AVY
AXON
BKR
BALL
BAC
BAX
BDX
BRK.B
BBY
TECH
BIIB
BLK
BX
XYZ
BK
BA
BKNG
BSX
BMY
AVGO
BR
BRO
BF.B
BLDR
BG
BXP
CHRW
CDNS
CPT
CPB
COF
CAH
CCL
CARR
CVNA
CAT
CBOE
CBRE
CDW
COR
CNC
CNP
CF
CRL
SCHW
CHTR
CVX
CMG
CB
CHD
CIEN
CI
CINF
CTAS
CSCO
C
CFG
CLX
CME
CMS
KO
CTSH
COIN
CL
CMCSA
FIX
CAG
COP
ED
STZ
CEG
COO
CPRT
GLW
CPAY
CTVA
CSGP
COST
CTRA
CRH
CRWD
CCI
CSX
CMI
CVS
DHR
DRI
DDOG
DVA
DECK
DE
DELL
DAL
DVN
DXCM
FANG
DLR
DG
DLTR
D
DPZ
DASH
DOV
DOW
DHI
DTE
DUK
DD
ETN
EBAY
ECL
EIX
EW
EA
ELV
EME
EMR
ETR
EOG
EPAM
EQT
EFX
EQIX
EQR
ERIE
ESS
EL
EG
EVRG
ES
EXC
EXE
EXPE
EXPD
EXR
XOM
FFIV
FDS
FICO
FAST
FRT
FDX
FIS
FITB
FSLR
FE
FISV
F
FTNT
FTV
FOXA
FOX
BEN
FCX
GRMN
IT
GE
GEHC
GEV
GEN
GNRC
GD
GIS
GM
GPC
GILD
GPN
GL
GDDY
GS
HAL
HIG
HAS
HCA
DOC
HSIC
HSY
HPE
HLT
HOLX
HD
HON
HRL
HST
HWM
HPQ
HUBB
HUM
HBAN
HII
IBM
IEX
IDXX
ITW
INCY
IR
PODD
INTC
IBKR
ICE
IFF
IP
INTU
ISRG
IVZ
INVH
IQV
IRM
JBHT
JBL
JKHY
J
JNJ
JCI
JPM
KVUE
KDP
KEY
KEYS
KMB
KIM
KMI
KKR
KLAC
KHC
KR
LHX
LH
LRCX
LW
LVS
LDOS
LEN
LII
LLY
LIN
LYV
LMT
L
LOW
LULU
LYB
MTB
MPC
MAR
MRSH
MLM
MAS
MA
MTCH
MKC
MCD
MCK
MDT
MRK
META
MET
MTD
MGM
MCHP
MU
MSFT
MAA
MRNA
MOH
TAP
MDLZ
MPWR
MNST
MCO
MS
MOS
MSI
MSCI
NDAQ
NTAP
NFLX
NEM
NWSA
NWS
NEE
NKE
NI
NDSN
NSC
NTRS
NOC
NCLH
NRG
NUE
NVDA
NVR
NXPI
ORLY
OXY
ODFL
OMC
ON
OKE
ORCL
OTIS
PCAR
PKG
PLTR
PANW
PSKY
PH
PAYX
PAYC
PYPL
PNR
PEP
PFE
PCG
PM
PSX
PNW
PNC
POOL
PPG
PPL
PFG
PG
PGR
PLD
PRU
PEG
PTC
PSA
PHM
PWR
QCOM
DGX
Q
RL
RJF
RTX
O
REG
REGN
RF
RSG
RMD
RVTY
HOOD
ROK
ROL
ROP
ROST
RCL
SPGI
CRM
SNDK
SBAC
SLB
STX
SRE
NOW
SHW
SPG
SWKS
SJM
SW
SNA
SOLV
SO
LUV
SWK
SBUX
STT
STLD
STE
SYK
SMCI
SYF
SNPS
SYY
TMUS
TROW
TTWO
TPR
TRGP
TGT
TEL
TDY
TER
TSLA
TXN
TPL
TXT
TMO
TJX
TKO
TTD
TSCO
TT
TDG
TRV
TRMB
TFC
TYL
TSN
USB
UBER
UDR
ULTA
UNP
UAL
UPS
URI
UNH
UHS
VLO
VTR
VLTO
VRSN
VRSK
VZ
VRTX
VTRS
VICI
V
VST
VMC
WRB
GWW
WAB
WMT
DIS
WBD
WM
WAT
WEC
WFC
WELL
WST
WDC
WY
WSM
WMB
WTW
WDAY
WYNN
XEL
XYL
YUM
ZBRA
ZBH
ZTS

        date         account         value ticker
0 2025-12-31  Free Cash Flow  1.396000e+09    MMM
1 2024-12-31  Free Cash Flow  6.380000e+08    MMM
2 2023-12-31  Free Cash Flow  5.065000e+09    MMM
3 2022-12-31  Free Cash Flow  3.842000e+09    MMM
4 2021-12-31  Free Cash Flow           NaN    MMM

**Nota importante:** Los datos obtenidos de `yfinance` suelen estar desestructurados, tanto en su formato como en su contenido. Las diferentes secciones de cashflow no están correctamente ordenadas ni clasificadas, sino que aparecen de manera aleatoria.

A continuación, se muestra un ejemplo:

In [4]:
print(df_cash_flow['account'].unique())

['Free Cash Flow' 'Repurchase Of Capital Stock' 'Repayment Of Debt'
 'Issuance Of Debt' 'Capital Expenditure'
 'Interest Paid Supplemental Data' 'Income Tax Paid Supplemental Data'
 'End Cash Position' 'Other Cash Adjustment Outside Changein Cash'
 'Beginning Cash Position' 'Effect Of Exchange Rate Changes'
 'Changes In Cash' 'Financing Cash Flow'
 'Cash Flow From Continuing Financing Activities'
 'Net Other Financing Charges' 'Proceeds From Stock Option Exercised'
 'Cash Dividends Paid' 'Common Stock Dividend Paid'
 'Net Common Stock Issuance' 'Common Stock Payments'
 'Net Issuance Payments Of Debt' 'Net Short Term Debt Issuance'
 'Net Long Term Debt Issuance' 'Long Term Debt Payments'
 'Long Term Debt Issuance' 'Investing Cash Flow'
 'Cash Flow From Continuing Investing Activities'
 'Net Other Investing Changes' 'Net Investment Purchase And Sale'
 'Sale Of Investment' 'Purchase Of Investment'
 'Net Business Purchase And Sale' 'Sale Of Business'
 'Purchase Of Business' 'Net PPE Purchase And Sale' 'Sale Of PPE'
 'Purchase Of PPE' 'Operating Cash Flow'
 'Cash Flow From Continuing Operating Activities'
 'Change In Working Capital' 'Change In Payables And Accrued Expense'
 'Change In Payable' 'Change In Account Payable' 'Change In Tax Payable'
 'Change In Income Tax Payable' 'Change In Inventory'
 'Change In Receivables' 'Changes In Account Receivables'
 'Other Non Cash Items' 'Stock Based Compensation'
 'Asset Impairment Charge' 'Deferred Tax' 'Deferred Income Tax'
 'Depreciation Amortization Depletion' 'Depreciation And Amortization'
 'Operating Gains Losses' 'Pension And Employee Benefit Expense'
 'Gain Loss On Sale Of Business' 'Net Income From Continuing Operations'
 'Capital Expenditure Reported' 'Change In Other Working Capital'
 'Change In Other Current Assets' 'Change In Accrued Expense'
 'Change In Prepaid Assets' 'Amortization Cash Flow'
 'Amortization Of Intangibles' 'Depreciation'
 'Gain Loss On Investment Securities' 'Short Term Debt Payments'
 'Short Term Debt Issuance' 'Provisionand Write Offof Assets'
 'Issuance Of Capital Stock' 'Common Stock Issuance'
 'Change In Other Current Liabilities'
 'Unrealized Gain Loss On Investment Securities'
 'Gain Loss On Sale Of PPE' 'Cash From Discontinued Investing Activities'
 'Cash From Discontinued Operating Activities'
 'Earnings Losses From Equity Investments'
 'Other Cash Adjustment Inside Changein Cash'
 'Net Preferred Stock Issuance' 'Preferred Stock Issuance'
 'Net Foreign Currency Exchange Gain Loss' 'Amortization Of Securities'
 'Net Intangibles Purchase And Sale' 'Purchase Of Intangibles'
 'Cash From Discontinued Financing Activities'
 'Preferred Stock Dividend Paid' 'Dividend Received Cfo'
 'Preferred Stock Payments' 'Net Investment Properties Purchase And Sale'
 'Sale Of Investment Properties' 'Purchase Of Investment Properties'
 'Change In Interest Payable' 'Dividends Received Cfi'
 'Cash Flow From Discontinued Operation' 'Sale Of Intangibles'
 'Excess Tax Benefit From Stock Based Compensation'
 'Interest Received Cfi' 'Depletion' 'Interest Paid Cff'
 'Taxes Refund Paid' 'Interest Paid Cfo'
 'Cash Flowsfromusedin Operating Activities Direct'
 'Classesof Cash Payments' 'Other Cash Paymentsfrom Operating Activities'
 'Paymentson Behalfof Employees'
 'Classesof Cash Receiptsfrom Operating Activities'
 'Other Cash Receiptsfrom Operating Activities' 'Dividend Paid Cfo']

In [ ]:
#Ejemplo de cómo descargar los datos de balance de un ticker específico (por ejemplo, 'META' para Meta Platforms, Inc.)

stock = yf.Ticker('META')
#Dentro de cada iteración, vamos a descargar los datos de cash flow de cada ticker, en todos los años disponibles que tengamos y lo añadiremos a la tabla
cash_flow_ticker = stock.cashflow
# cash_flow_ticker.T.reset_index().melt(id_vars='index', var_name='Account', value_name='Value')  # Unpivoting
cash_flow_ticker.to_excel(f'cashflow_{stock}.xlsx', index=False) 
# a la hora descargar en excel podemos tener un nombre de archivo dinámico con el ticker incluido para identificarlo fácilmente, en este caso se guardará como cashflow_META.xlsx
# usamos {} para incluir el valor de la variable stock (que es el ticker) dentro del nombre del archivo al guardarlo en Excel. 
# si cambiamos el ticker a 'AAPL' se guardará como cashflow_AAPL.xlsx

,2025-12-31,2024-12-31,2023-12-31,2022-12-31,2021-12-31
Free Cash Flow,4.610900e+10,5.407200e+10,4.406800e+10,1.928900e+10,NaN
Repurchase Of Capital Stock,-2.624800e+10,-3.012500e+10,-1.977400e+10,-2.795600e+10,NaN
Repayment Of Debt,-2.524000e+09,-1.969000e+09,-1.058000e+09,-8.500000e+08,NaN
Issuance Of Debt,2.990600e+10,1.043200e+10,8.455000e+09,9.921000e+09,NaN
Capital Expenditure,-6.969100e+10,-3.725600e+10,-2.704500e+10,-3.118600e+10,NaN
Interest Paid Supplemental Data,6.960000e+08,4.860000e+08,4.480000e+08,0.000000e+00,NaN
Income Tax Paid Supplemental Data,7.578000e+09,1.055400e+10,6.607000e+09,6.407000e+09,NaN
End Cash Position,3.910000e+10,4.543800e+10,4.282700e+10,1.559600e+10,NaN
Beginning Cash Position,4.543800e+10,4.282700e+10,1.559600e+10,1.686500e+10,NaN
Effect Of Exchange Rate Changes,2.350000e+08,-7.860000e+08,1.130000e+08,-6.380000e+08,NaN
Changes In Cash,-6.573000e+09,3.397000e+09,2.711800e+10,-6.310000e+08,NaN
Financing Cash Flow,-2.037000e+10,-4.078100e+10,-1.950000e+10,-2.213600e+10,NaN
Cash Flow From Continuing Financing Activities,-2.037000e+10,-4.078100e+10,-1.950000e+10,-2.213600e+10,NaN
Net Other Financing Charges,-1.618000e+10,-1.404700e+10,-7.123000e+09,-3.251000e+09,NaN
Cash Dividends Paid,-5.324000e+09,-5.072000e+09,0.000000e+00,0.000000e+00,NaN
Common Stock Dividend Paid,-5.324000e+09,-5.072000e+09,0.000000e+00,0.000000e+00,NaN
Net Common Stock Issuance,-2.624800e+10,-3.012500e+10,-1.977400e+10,-2.795600e+10,NaN
Common Stock Payments,-2.624800e+10,-3.012500e+10,-1.977400e+10,-2.795600e+10,NaN
Net Issuance Payments Of Debt,2.738200e+10,8.463000e+09,7.397000e+09,9.071000e+09,NaN
Net Short Term Debt Issuance,NaN,NaN,NaN,NaN,14000000.0
Net Long Term Debt Issuance,2.738200e+10,8.463000e+09,7.397000e+09,9.071000e+09,NaN
Long Term Debt Payments,-2.524000e+09,-1.969000e+09,-1.058000e+09,-8.500000e+08,NaN
Long Term Debt Issuance,2.990600e+10,1.043200e+10,8.455000e+09,9.921000e+09,NaN
Investing Cash Flow,-1.020030e+11,-4.715000e+10,-2.449500e+10,-2.897000e+10,NaN
Cash Flow From Continuing Investing Activities,-1.020030e+11,-4.715000e+10,-2.449500e+10,-2.897000e+10,NaN
Net Other Investing Changes,-2.250000e+09,1.400000e+08,-2.200000e+07,-4.000000e+06,NaN
Net Investment Purchase And Sale,-2.838500e+10,-9.764000e+09,3.201000e+09,3.532000e+09,NaN
Sale Of Investment,2.687400e+10,1.578900e+10,6.184000e+09,1.315800e+10,NaN
Purchase Of Investment,-5.525900e+10,-2.555300e+10,-2.983000e+09,-9.626000e+09,NaN
Net Business Purchase And Sale,-1.677000e+09,-2.700000e+08,-6.290000e+08,-1.312000e+09,NaN
Sale Of Business,2.554000e+09,0.000000e+00,0.000000e+00,NaN,NaN
Purchase Of Business,-4.231000e+09,-2.700000e+08,-6.290000e+08,-1.312000e+09,NaN
Net PPE Purchase And Sale,-6.969100e+10,-3.725600e+10,-2.704500e+10,-3.118600e+10,NaN
Sale Of PPE,NaN,NaN,2.210000e+08,2.450000e+08,123000000.0
Purchase Of PPE,-6.969100e+10,-3.725600e+10,-2.704500e+10,-3.118600e+10,NaN
Operating Cash Flow,1.158000e+11,9.132800e+10,7.111300e+10,5.047500e+10,NaN
Cash Flow From Continuing Operating Activities,1.158000e+11,9.132800e+10,7.111300e+10,5.047500e+10,NaN
Change In Working Capital,-8.850000e+08,1.048000e+09,3.836000e+09,5.683000e+09,NaN
Change In Other Working Capital,NaN,NaN,NaN,NaN,187000000.0
Change In Other Current Liabilities,4.370000e+08,2.805000e+09,6.240000e+08,8.860000e+08,NaN
Change In Other Current Assets,-4.810000e+08,-2.700000e+08,-8.000000e+07,-1.060000e+08,NaN
Change In Payables And Accrued Expense,1.063000e+09,6.960000e+08,5.132000e+09,4.510000e+09,NaN
Change In Accrued Expense,1.077000e+09,3.230000e+08,5.081000e+09,4.300000e+09,NaN
Change In Payable,-1.400000e+07,3.730000e+08,5.100000e+07,2.100000e+08,NaN
Change In Account Payable,-1.400000e+07,3.730000e+08,5.100000e+07,2.100000e+08,NaN
Change In Prepaid Assets,-8.900000e+07,-6.980000e+08,5.590000e+08,1.620000e+08,NaN
Change In Receivables,-1.815000e+09,-1.485000e+09,-2.399000e+09,2.310000e+08,NaN
Changes In Account Receivables,-1.815000e+09,-1.485000e+09,-2.399000e+09,2.310000e+08,NaN
Other Non Cash Items,-4.160000e+08,1.400000e+08,3.090000e+08,1.982000e+09,NaN
Stock Based Compensation,2.042700e+10,1.669000e+10,1.402700e+10,1.199200e+10,NaN
Unrealized Gain Loss On Investment Securities,-1.138000e+09,-5.300000e+07,1.020000e+08,4.630000e+08,NaN
Asset Impairment Charge,0.000000e+00,3.830000e+08,2.432000e+09,2.218000e+09,NaN
Deferred Tax,1.873800e+10,-4.738000e+09,1.310000e+08,-3.286000e+09,NaN
Deferred Income Tax,1.873800e+10,-4.738000e+09,1.310000e+08,-3.286000e+09,NaN
Depreciation Amortization Depletion,1.861600e+10,1.549800e+10,1.117800e+10,8.686000e+09,NaN
Depreciation And Amortization,1.861600e+10,1.549800e+10,1.117800e+10,8.686000e+09,NaN
Net Income From Continuing Operations,6.045800e+10,6.236000e+10,3.909800e+10,2.320000e+10,NaN

**3. Descargamos en Excel los datos**

In [8]:
## descargamos el excel sin el índice
df_cash_flow.to_excel('cashflow.xlsx', index=False)

**Fin del módulo**